algo = input('digite algo:')
print('ele é um numero?',algo.isnumeric())
print( 'ele é decimal?',algo.isdecimal())
print('ele é uma letra?',algo.isalpha())
print('ele está em letra minuscula?',algo.islower())
print('ele é um espaço?',algo.isspace())
print('ele está em letra maiuscula?',algo.isupper())
print('ele é um digito?',algo.isdigit())
print('ele está capitalizado?',algo.istitle())
print('qual o seu tipo primitivo?',type(algo))